### PR TITLE
Updated content to run in Unity 5.6 and fixed the walking animation!

### PR DESCRIPTION
**Pull request by theWildSushii**
I know this is a kinda old project (last commit was four years ago), but I saw it and I wanted to help a little bit :)

Unity automatically updated the project and scripts to fit the current version of Unity (5.6). I updated some things manually too.

I removed the player walking script and replaced it using Unity´s Animator to handle the walking animation.

A day-night cycle was added too.

I copied the .gitignore file from another Unity project and added it here.

### CODE REVIEW

**Comment by devmattrick** [comment]
You're awesome! Thank you very much!

**Comment by theWildSushii** [comment]
Is this project still alive? I would like to help more often if you need to ;) seems interesting

**Comment by devmattrick** [comment]
I'm not super interested in maintaining it at the moment, but I can add you as a contributor if you'd like or you can maintain your own fork :P

**Comment by theWildSushii** [comment]
I'm ok with the fork, once in a while I'll send you pull requests if you
want

On 17 Jun 2017 8:06 pm, "mattrick" <notifications@github.com> wrote:

I'm not super interested in maintaining it at the moment, but I can add you
as a contributor if you'd like or you can maintain your own fork :P

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/devmattrick/Mine-In-Unity/pull/3#issuecomment-309251810>,
or mute the thread

**Comment by devmattrick** [comment]
Added a link to your fork :D

**Pull request merged**
